### ISSUE TITLE
(PQ25) Cluster shows multiple warning lights and doesn't respond to ESP-Dash commands

### ISSUE THREAD

**Issue by Madsgaming08** [r00li/CarCluster#10] opened 2024-07-01 19:45 UTC
Hello. I found this project about 1 month ago and thought it would be a cool thing to have. 

All wires and boards have been connected and all libraries and the board manager from the project are installed as explained.

On power up, the cluster showed many warning lights (Video attached). 
https://github.com/r00li/CarCluster/assets/173914295/8ac98a34-0185-4e48-b3ff-1c6b81cd84a9
Despite connecting the dash, the cluster did not react to the inputs, e.g. indicators. Also during testing, the esp32 board started flashing blue (Video attached).
https://github.com/r00li/CarCluster/assets/173914295/a4d684ac-7017-43c4-bf87-02e7d9d920f7

Multiple times disconnecting and reconnecting wires, double checking pins and voltage inputs and updating packages and flashing the esp32 board, later, I have made zero progress. 

Any idea what's causing this issue?

**Comment by r00li** [comment] 2024-07-01 20:41
Hmmm, that's an interesting one. 
Let's begin with the simple one - if you have a CAN termination resistor try removing/disabling it. If you don't have it, then enable/add it. I think generally the Polo cluster for me was quite happy with either, but I can't remember. Generally most clusters need it.

Once you tested the termination resistor, try opening the serial monitor and send this to the ESP:
```{"action":10, "spe":54, "gea":"2", "rpm":3590, "mrp":7999, "lft":0, "rit":0, "oit":0, "pau":0, "run":0, "fue":0, "hnb":0, "abs":0, "tra":0}```
Let's see if things on the cluster move 😄 . This way we can check if the issue is in the web dashboard or something else.

But the termination resistor is my first thought here. Let me know how it goes.

**Comment by r00li** [comment] 2024-08-22 22:28
Awesome, thanks for letting me know.
Closing the issue then.

**Closed by r00li** 2024-08-22 22:28 UTC
